version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: 'docker'
    directory: '/'
    ignore:
      - dependency-name: "node"
        # Node 27+ will all be LTS releases
        versions: [ "21", "23", "25" ]
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
