services:
  epb-prototypes:
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/usr/src/app
