version: 0.2

phases:
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - bash ./scripts/assume_role.sh arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server thisProfile
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --profile thisProfile

  post_build:
    commands:

